### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

@host=http://localhost:8080


###

GET {{host}}

###

GET {{host}}/api/tacos?recent


###

GET {{host}}/api/tacos/1


###

POST {{host}}/api/tacos
Content-Type: application/json

{
  "name": "aa12345",
  "ingredients": [
    {
      "id": "FLTO",
      "name": "Flour Tortilla",
      "type": "WRAP"
    },
    {
      "id": "GRBF",
      "name": "Ground Beef",
      "type": "PROTEIN"
    }]
}

###


GET {{host}}/data-api

###

GET {{host}}/data-api/ingredients

###

GET {{host}}/data-api/ingredients/FLTO

###

GET {{host}}/data-api/tacos

###


GET {{host}}/api/tacos/ingredient/FLTO

###


GET {{host}}/api/ingredients

###

POST {{host}}/api/ingredients
Content-Type: application/json

{
  "id": "FISH",
  "name": "Stinky Fish",
  "type": "PROTEIN"
}