spring:
  application:
    name: JavaTacoCloud

  datasource:
    generate-unique-name: false
    name: tacocloud
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pw-1234
  data:
    rest:
      base-path: /data-api
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    template:
      default-topic: tacocloud.order.queue

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#  artemis:
#    broker-url: tcp://127.0.0.1:61616
#    user: artemis
#    password: artemis
#
#  jms:
#    template:
#      default-destination: tacocloud.order.queue

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update


taco:
  orders:
    page-size: 10

